/* Copyright (C) 2019-2021 Thomas "Kimimaru" Deeb
 * 
 * This file is part of TRBot, software for playing games through text.
 *
 * TRBot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * TRBot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with TRBot.  If not, see <https://www.gnu.org/licenses/>.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <linux/input.h>
#include <linux/uinput.h>
#include <libevdev/libevdev.h>
#include <libevdev/libevdev-uinput.h>

#define MIN_CONTROLLERS 1
#define MAX_CONTROLLERS 16
#define INVALID_CONTROLLER NULL

#define MIN_AXIS_VAL -32767
#define MAX_AXIS_VAL 32767

//Axis "fuzz" means padding
//uinput will drop events generated by the device driver
//if the difference from the last value is lower than the fuzz
#define AXIS_FUZZ 0 

//Axis "flat" is essentially the deadzone
#define AXIS_FLAT 0

//This struct serves to store both pointers so they can be freed later
struct libholder
{
    struct libevdev* dev;
    struct libevdev_uinput* uidev;
};

int GetMinControllers();
int GetMaxControllers();

int GetMinAxisVal();
int GetMaxAxisVal();

void UpdateJoystick(struct libholder* libholder);

void PressReleaseButton(struct libholder* libholder, int button, int press);

void PressAxis(struct libholder* libholder, int axis, int value);

struct libholder* CreateController(int index);

void CloseController(struct libholder* libholder);